---
- name: check for cgroup modifications
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^.*cgroup_enable=memory cgroup_memory=1.*$'
    state: absent
  check_mode: true
  changed_when: false
  register: cmdline_cgroup_string

- name: insert cgroup flags to kernel command line parameters
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: true
  when: not cmdline_cgroup_string.found

- name: notify handler to reboot os if needed
  when: not cmdline_cgroup_string.found
  debug:
    msg: "rebooting {{ inventory_hostname }}"
  changed_when: true
  notify: Reboot OS

- name: Flush handlers
  meta: flush_handlers
