---
- name: Fail if not running on Ubuntu 24.x
  fail: msg="These tasks should only be run on Ubuntu 24.x servers"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version|int != 24
