---

- name: Install microk8s snap
  snap:
    state: present
    name:
      - microk8s
    classic: true
    channel: "{{ microk8s_version | default('stable') }}"

- name: Microk8s status
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.status --wait-ready
  args:
    executable: /bin/bash
  changed_when: false

- name: Allow Privileged for Kubelet (needed by Elasticsearch Helm chart)
  lineinfile:
    dest: /var/snap/microk8s/current/args/kubelet
    line: "--allow-privileged=true"
    state: absent

- name: Allow Privileged for K8s Apiserver (needed by Elasticsearch Helm chart)
  lineinfile:
    dest: /var/snap/microk8s/current/args/kube-apiserver
    line: "--allow-privileged=true"
    state: present

- name: Set File Descriptor Limits for Microk8s
  lineinfile:
    dest: /var/snap/microk8s/current/args/containerd-env
    line: "ulimit -n 65536"
    state: present

- name: setup containerd, Add Insecure Registries
  import_tasks: add-insecure-registries.yml

- name: Stop Microk8s
  shell: |
    source /etc/profile.d/apps-bin-path.sh && microk8s.stop
    sleep 5
  args:
    executable: /bin/bash
  changed_when: false

- name: Start Microk8s
  shell: |
    source /etc/profile.d/apps-bin-path.sh && microk8s.start
    sleep 15
  args:
    executable: /bin/bash
  changed_when: false

- name: Microk8s status
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.status --wait-ready
  args:
    executable: /bin/bash
  changed_when: false

- name: Alias kubectl
  shell: "source /etc/profile.d/apps-bin-path.sh && snap alias microk8s.kubectl kubectl"
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable dns
  shell: "source /etc/profile.d/apps-bin-path.sh && microk8s.enable dns"
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable ingress
  shell: "source /etc/profile.d/apps-bin-path.sh && microk8s.enable ingress"
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable storage
  shell: "source /etc/profile.d/apps-bin-path.sh && microk8s.enable storage"
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable K8s Dashboard
  shell: "source /etc/profile.d/apps-bin-path.sh && /snap/bin/microk8s.enable dashboard"
  when: k8s_dashboard|default(False)|bool == True
  args:
    executable: /bin/bash
  changed_when: false
