---
- name: Install pre-requisite packages
  apt:
    state: present
    name:
      - python3
      - python3-pip
      - snapd
      - locate
      - emacs-nox
      - tree

- name: Remove httpd to free up port 8080
  apt:
    state: absent
    name:
      - apache2

- name: Apparmor must be started
  service:
    name: apparmor
    state: started
